import type { Resource } from '../types';

export const designAndUI: Resource[] = [
  {
    name: 'Lucide Icons',
    preview: '/previews/lucide.png',
    description:
      'Lucide is a collection of open-source icons designed to be simple and consistent.',
    link: 'https://lucide.dev',
    tags: ['icon', 'design', 'open-source'],
  },
  {
    name: 'Mobbin',
    preview: '/previews/mobbin.png',
    description: 'A design library with a collection of mobile app designs and patterns.',
    link: 'https://mobbin.com',
    tags: ['design', 'typography'],
  },
  {
    name: 'Carbon',
    preview: '/previews/carbon.png',
    description: 'A desktop application for creating beautiful images of your source code.',
    link: 'https://carbon.now.sh',
    tags: ['dev', 'design', 'open-source', 'terminal'],
  },
  {
    name: 'Tailwind CSS',
    preview: '/previews/tailwind-css.png',
    description: 'A utility-first CSS framework for creating modern and responsive web designs.',
    link: 'https://tailwindcss.com',
    tags: ['dev', 'design', 'open-source'],
  },
  {
    name: 'Boring Avatars',
    preview: '/previews/boring-avatars.png',
    description: 'A collection of simple, customizable avatars for use in web applications.',
    link: 'https://boringavatars.com',
    tags: ['dev', 'design', 'open-source'],
  },
  {
    name: 'Lottie Files',
    preview: '/previews/lottie-files.png',
    description:
      'A library for rendering animations created with Adobe After Effects in web applications.',
    link: 'https://github.com/lottiefiles',
    tags: ['dev', 'design', 'open-source'],
  },
  {
    name: 'Unsplash',
    preview: '/previews/unsplash.png',
    description:
      'A platform for finding and sharing high-quality, free-to-use images for your projects.',
    link: 'https://unsplash.com',
    tags: ['design'],
  },
  {
    name: 'Deck Gallery',
    preview: '/previews/deck-gallery.png',
    description: 'A collection of beautifully designed decks, slides, keynotes, guidelines, etc.',
    link: 'https://deck.gallery',
    tags: ['design'],
  },
  {
    name: 'Happy Hues',
    preview: '/previews/happy-hues.png',
    description:
      'A curated collection of color palettes and design inspiration for web designers and developers.',
    link: 'https://www.happyhues.co',
    tags: ['design', 'typography'],
  },
  {
    name: 'Tailwind Buttons - ibelick',
    preview: '/previews/tailwind-buttons-ibelick.png',
    description: 'A collection of beautifully designed buttons using Tailwind CSS.',
    link: 'https://buttons.ibelick.com',
    tags: ['dev', 'design', 'open-source'],
  },
  {
    name: 'CSS Unit Converter',
    preview: '/previews/css-unit-converter.png',
    link: 'https://cssunitconverter.com/',
    description: 'Convert CSS units like px to em',
    tags: ['design', 'dev'],
  },
  {
    name: 'Colorffy',
    description: 'A color palette generator for designers and developers.',
    preview: '/previews/colorffy.png',
    link: 'https://colorffy.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Design System Checklist',
    description: 'A checklist to ensure your design system is comprehensive and well-documented.',
    preview: '/previews/design-system-checklist.png',
    link: 'https://designsystemchecklist.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Ingradients',
    description: 'A gallery of mesh gradients.',
    preview: '/previews/ingradients.png',
    link: 'https://ingradients.net/',
    tags: ['design'],
  },
  {
    name: 'Design Gradients',
    description: 'A collection of beautiful gradients for your designs.',
    preview: '/previews/design-gradients.png',
    link: 'https://designgradients.com/',
    tags: ['design'],
  },
  {
    name: 'Paper Sizes',
    description: 'A collection of common paper sizes and dimensions.',
    preview: '/previews/paper-sizes.png',
    link: 'https://papersizes.io/',
    tags: ['design'],
  },
  {
    name: 'Shoot',
    description: 'A collection of app screenshots for design inspiration.',
    preview: '/previews/shoot.png',
    link: 'https://shoot.design/',
    tags: ['design'],
  },
  {
    name: 'Navbar Gallery',
    description: 'A collection of beautifully designed navigation bars for your applications.',
    preview: '/previews/navbar-gallery.png',
    link: 'https://navbar.gallery/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Colormind',
    description: 'A color scheme generator powered by AI.',
    preview: '/previews/colormind.png',
    link: 'https://colormind.io/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Brandmark',
    description: 'A logo design tool powered by AI.',
    preview: '/previews/brandmark.png',
    link: 'https://brandmark.io/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Huemint',
    description: 'A color palette generator powered by AI.',
    preview: '/previews/huemint.png',
    link: 'https://huemint.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Font Joy',
    description: 'A font pairing tool powered by AI.',
    preview: '/previews/font-joy.png',
    link: 'https://fontjoy.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Vecto3d',
    description: 'A 3D vector graphics tool.',
    preview: '/previews/vecto3d.png',
    link: 'https://vecto3d.xyz/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Fontscale',
    description: 'A tool for responsive font scaling.',
    preview: '/previews/fontscale.png',
    link: 'https://fontscale.joelfisher.me/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Animate UI',
    description: 'A library of fluid, animated components.',
    preview: '/previews/animate-ui.png',
    link: 'https://animate-ui.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Pattern Craft',
    description: 'A gallery of patterns and textures.',
    preview: '/previews/pattern-craft.png',
    link: 'https://patterncraft.fun/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Kibo UI',
    description: 'UI components based on shadcn/ui.',
    preview: '/previews/kibo-ui.png',
    link: 'https://kibo-ui.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'tweakcn',
    description: 'A tool for tweaking and customizing a shadcn/ui theme.',
    preview: '/previews/tweakcn.png',
    link: 'https://tweakcn.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'tailark',
    description: 'UI components based on shadcn/ui.',
    preview: '/previews/tailark.png',
    link: 'https://tailark.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'kokonut UI',
    description: 'A UI component library based on shadcn/ui.',
    preview: '/previews/kokonut-ui.png',
    link: 'https://kokonutui.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Radix',
    description: 'A set of high-quality, accessible UI components.',
    preview: '/previews/radix.png',
    link: 'https://radix-ui.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Shadcn/ui',
    description: 'A set of high-quality, accessible UI components.',
    preview: '/previews/shadcn-ui.png',
    link: 'https://ui.shadcn.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Tinte.dev',
    description: 'A tool for creating and managing a shadcn/ui theme.',
    preview: '/previews/tinte-dev.png',
    link: 'https://tinte.dev/shadcn',
    tags: ['design', 'dev'],
  },
  {
    name: 'Resourceboy',
    preview: '/previews/resourceboy.png',
    description: 'A collection of fonts, textures, mockups, patterns and more.',
    link: 'https://resourceboy.com/',
    tags: ['design'],
  },
  {
    name: 'Paletton',
    preview: '/previews/paletton.png',
    description: 'A color scheme designer for web applications.',
    link: 'https://paletton.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Thumb Craftwork',
    preview: '/previews/thumb-craftwork.png',
    link: 'https://thumb.craftwork.design/',
    description: 'Tool to create nice thumbnails or images.',
    tags: ['design'],
  },
  {
    name: 'Realtime Colors',
    preview: '/previews/realtime-colors.png',
    description: 'A tool for creating and visualizing color palettes in real-time.',
    link: 'https://realtimecolors.com/',
    tags: ['design', 'dev'],
  },
];
