import type { Resource } from '../types';

export const designAndUI: Resource[] = [
  {
    name: 'Lucide Icons',
    preview: '/previews/lucide.png',
    description:
      'Lucide is a collection of open-source icons designed to be simple and consistent.',
    link: 'https://lucide.dev',
    tags: ['icon', 'design', 'open-source'],
  },
  {
    name: 'Mobbin',
    preview: '/previews/mobbin.png',
    description: 'A design library with a collection of mobile app designs and patterns.',
    link: 'https://mobbin.com',
    tags: ['design', 'typography'],
  },
  {
    name: 'Carbon',
    preview: '/previews/carbon.png',
    description: 'A desktop application for creating beautiful images of your source code.',
    link: 'https://carbon.now.sh',
    tags: ['dev', 'design', 'open-source', 'terminal'],
  },
  {
    name: 'Tailwind CSS',
    preview: '/previews/tailwind-css.png',
    description: 'A utility-first CSS framework for creating modern and responsive web designs.',
    link: 'https://tailwindcss.com',
    tags: ['dev', 'design', 'open-source'],
  },
  {
    name: 'Boring Avatars',
    preview: '/previews/boring-avatars.png',
    description: 'A collection of simple, customizable avatars for use in web applications.',
    link: 'https://boringavatars.com',
    tags: ['dev', 'design', 'open-source'],
  },
  {
    name: 'Lottie Files',
    preview: '/previews/lottie-files.png',
    description:
      'A library for rendering animations created with Adobe After Effects in web applications.',
    link: 'https://github.com/lottiefiles',
    tags: ['dev', 'design', 'open-source'],
  },
  {
    name: 'Unsplash',
    preview: '/previews/unsplash.png',
    description:
      'A platform for finding and sharing high-quality, free-to-use images for your projects.',
    link: 'https://unsplash.com',
    tags: ['design'],
  },
  {
    name: 'Deck Gallery',
    preview: '/previews/deck-gallery.png',
    description: 'A collection of beautifully designed decks, slides, keynotes, guidelines, etc.',
    link: 'https://deck.gallery',
    tags: ['design'],
  },
  {
    name: 'Happy Hues',
    preview: '/previews/happy-hues.png',
    description:
      'A curated collection of color palettes and design inspiration for web designers and developers.',
    link: 'https://www.happyhues.co',
    tags: ['design', 'typography'],
  },
  {
    name: 'Tailwind Buttons - ibelick',
    preview: '/previews/tailwind-buttons-ibelick.png',
    description: 'A collection of beautifully designed buttons using Tailwind CSS.',
    link: 'https://buttons.ibelick.com',
    tags: ['dev', 'design', 'open-source'],
  },
  {
    name: 'CSS Unit Converter',
    preview: '/previews/css-unit-converter.png',
    link: 'https://cssunitconverter.com/',
    description: 'Convert CSS units like px to em',
    tags: ['design', 'dev'],
  },
  {
    name: 'Colorffy',
    description: 'A color palette generator for designers and developers.',
    preview: '/previews/colorffy.png',
    link: 'https://colorffy.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Design System Checklist',
    description: 'A checklist to ensure your design system is comprehensive and well-documented.',
    preview: '/previews/design-system-checklist.png',
    link: 'https://designsystemchecklist.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Ingradients',
    description: 'A gallery of mesh gradients.',
    preview: '/previews/ingradients.png',
    link: 'https://ingradients.net/',
    tags: ['design'],
  },
  {
    name: 'Design Gradients',
    description: 'A collection of beautiful gradients for your designs.',
    preview: '/previews/design-gradients.png',
    link: 'https://designgradients.com/',
    tags: ['design'],
  },
  {
    name: 'Paper Sizes',
    description: 'A collection of common paper sizes and dimensions.',
    preview: '/previews/paper-sizes.png',
    link: 'https://papersizes.io/',
    tags: ['design'],
  },
  {
    name: 'Shoot',
    description: 'A collection of app screenshots for design inspiration.',
    preview: '/previews/shoot.png',
    link: 'https://shoot.design/',
    tags: ['design'],
  },
  {
    name: 'Navbar Gallery',
    description: 'A collection of beautifully designed navigation bars for your applications.',
    preview: '/previews/navbar-gallery.png',
    link: 'https://navbar.gallery/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Colormind',
    description: 'A color scheme generator powered by AI.',
    preview: '/previews/colormind.png',
    link: 'http://colormind.io/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Brandmark',
    description: 'A logo design tool powered by AI.',
    preview: '/previews/brandmark.png',
    link: 'https://brandmark.io/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Huemint',
    description: 'A color palette generator powered by AI.',
    preview: '/previews/huemint.png',
    link: 'https://huemint.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Font Joy',
    description: 'A font pairing tool powered by AI.',
    preview: '/previews/font-joy.png',
    link: 'https://fontjoy.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Vecto3d',
    description: 'A 3D vector graphics tool.',
    preview: '/previews/vecto3d.png',
    link: 'https://vecto3d.xyz/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Fontscale',
    description: 'A tool for responsive font scaling.',
    preview: '/previews/fontscale.png',
    link: 'https://fontscale.joelfisher.me/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Animate UI',
    description: 'A library of fluid, animated components.',
    preview: '/previews/animate-ui.png',
    link: 'https://animate-ui.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Pattern Craft',
    description: 'A gallery of patterns and textures.',
    preview: '/previews/pattern-craft.png',
    link: 'https://patterncraft.fun/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Kibo UI',
    description: 'UI components based on shadcn/ui.',
    preview: '/previews/kibo-ui.png',
    link: 'https://kibo-ui.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'tweakcn',
    description: 'A tool for tweaking and customizing a shadcn/ui theme.',
    preview: '/previews/tweakcn.png',
    link: 'https://tweakcn.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'tailark',
    description: 'UI components based on shadcn/ui.',
    preview: '/previews/tailark.png',
    link: 'https://tailark.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'kokonut UI',
    description: 'A UI component library based on shadcn/ui.',
    preview: '/previews/kokonut-ui.png',
    link: 'https://kokonutui.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Radix',
    description: 'A set of high-quality, accessible UI components.',
    preview: '/previews/radix.png',
    link: 'https://radix-ui.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Shadcn/ui',
    description: 'A set of high-quality, accessible UI components.',
    preview: '/previews/shadcn-ui.png',
    link: 'https://ui.shadcn.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Tinte.dev',
    description: 'A tool for creating and managing a shadcn/ui theme.',
    preview: '/previews/tinte-dev.png',
    link: 'https://tinte.dev/shadcn',
    tags: ['design', 'dev'],
  },
  {
    name: 'Resourceboy',
    preview: '/previews/resourceboy.png',
    description: 'A collection of fonts, textures, mockups, patterns and more.',
    link: 'https://resourceboy.com/',
    tags: ['design'],
  },
  {
    name: 'Paletton',
    preview: '/previews/paletton.png',
    description: 'A color scheme designer for web applications.',
    link: 'https://paletton.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Thumb Craftwork',
    preview: '/previews/thumb-craftwork.png',
    link: 'https://thumb.craftwork.design/',
    description: 'Tool to create nice thumbnails or images.',
    tags: ['design'],
  },
  {
    name: 'Realtime Colors',
    preview: '/previews/realtime-colors.png',
    description: 'A tool for creating and visualizing color palettes in real-time.',
    link: 'https://realtimecolors.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'SVG Wave Generator',
    preview: '/previews/svg-wave.png',
    description: 'A svg waves generator.',
    link: 'https://svgwave.in/',
    tags: ['design'],
  },
  {
    name: 'Blob Generator',
    preview: '/previews/blob-generator.png',
    description: 'A blob generator for creating unique and visually appealing shapes.',
    link: 'https://www.magicpattern.design/tools/blob-generator',
    tags: ['design'],
  },
  {
    name: 'Shape Divider',
    preview: '/previews/shape-divider.png',
    description: 'A tool for creating custom shape dividers for web designs.',
    link: 'https://www.shapedivider.app/',
    tags: ['design'],
  },
  {
    name: 'Add Grain to Image',
    preview: '/previews/add-grain-to-image.png',
    description: 'A tool for adding grain texture to images.',
    link: 'https://www.magicpattern.design/tools/add-grain-to-images',
    tags: ['design'],
  },
  {
    name: 'Fresh Folk',
    preview: '/previews/fresh-folk.png',
    description: 'An illustration library of people and objects.',
    link: 'https://fresh-folk.com/',
    tags: ['design'],
  },
  {
    name: 'Thiings',
    preview: '/previews/thiings.png',
    description: 'A collection of 3D illustrations and icons.',
    link: 'https://thiings.com/',
    tags: ['design'],
  },
  {
    name: 'Icones',
    preview: '/previews/icones.png',
    description: 'A collection of icon collections for personal and commercial use.',
    link: 'https://icones.js.org/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Get Illustra',
    preview: '/previews/getillustra.png',
    description: 'A gallery of illustrations for inspiration.',
    link: 'https://getillustra.com/',
    tags: ['design'],
  },
  {
    name: 'BrandGuidelines',
    preview: '/previews/brandguidelines.png',
    description: 'A collection of brand guidelines from various companies.',
    link: 'https://www.brandguidelines.net/',
    tags: ['design'],
  },
  {
    name: 'Sections.wtf',
    preview: '/previews/sections-wtf.png',
    description: 'A collection of website sections for inspiration.',
    link: 'https://sections.wtf/',
    tags: ['dev', 'design'],
  },
  {
    name: 'Doodle Ipsum',
    preview: '/previews/doodle-ipsum.png',
    description: 'A fun tool to generate random doodles for design inspiration or placeholders.',
    link: 'https://doodleipsum.com',
    tags: ['design'],
  },
  {
    name: 'Spotted in Prod',
    preview: '/previews/spotted-in-prod.png',
    description:
      'A curated collection of interesting and innovative web designs spotted in production, showcasing the latest trends and techniques in web development.',
    link: 'https://spottedinprod.com',
    tags: ['design', 'dev'],
  },
  {
    name: 'Dark Design',
    preview: '/previews/dark-design.png',
    description:
      'A curated collection of dark-themed web designs, showcasing the beauty and versatility of dark mode in web development.',
    link: 'https://dark.design',
    tags: ['design', 'dev'],
  },
  {
    name: 'SVG Chart Generator',
    preview: '/previews/svg-chart-generator.png',
    description:
      'A tool for generating SVG charts, allowing you to create customizable and visually appealing charts for your web applications.',
    link: 'https://www.magicpattern.design/tools/svg-chart-generator',
    tags: ['dev', 'design'],
  },
  {
    name: 'Mesh Gradient Generator',
    preview: '/previews/mesh-gradient-generator2.png',
    description: 'A tool for generating beautiful mesh gradients for your designs.',
    link: 'https://www.magicpattern.design/tools/mesh-gradients',
    tags: ['dev', 'design'],
  },
  {
    name: 'Polka Dot Pattern Generator',
    preview: '/previews/polka-dot-pattern-generator.png',
    description: 'A tool for generating customizable polka dot patterns for your designs.',
    link: 'https://www.magicpattern.design/tools/polka-dot-pattern-generator',
    tags: ['dev', 'design'],
  },
  {
    name: 'Seamless Pattern Generator',
    preview: '/previews/seamless-pattern-generator.png',
    description: 'A tool for generating seamless patterns for your designs.',
    link: 'https://www.magicpattern.design/tools/seamless-pattern-generator',
    tags: ['dev', 'design'],
  },
  {
    name: 'iOS Icon Gallery',
    preview: '/previews/ios-icon-gallery.png',
    description: 'A collection of iOS app icons for design inspiration and reference.',
    link: 'https://iosicongallery.com',
    tags: ['design', 'dev'],
  },
  {
    name: 'Viewport UI',
    preview: '/previews/viewport-ui.png',
    description: 'UI curated experiences for you inspiration.',
    link: 'https://viewport-ui.design/',
    tags: ['design', 'dev'],
  },
  {
    name: '404s Design',
    preview: '/previews/404s-design.png',
    description: 'A curated collection of creative and innovative 404 error page designs.',
    link: 'https://404s.design',
    tags: ['design', 'dev'],
  },
];
