import type { Tool } from '.';

const pendingSortTools: Tool[] = [
  {
    name: 'CSS Unit Converter',
    preview: 'css-unit-converter.png',
    link: 'https://cssunitconverter.com/',
    description: 'Convert CSS units like px to em',
    tags: ['design', 'dev'],
  },
  {
    name: 'Colorffy',
    description: 'A color palette generator for designers and developers.',
    preview: 'colorffy.png',
    link: 'https://colorffy.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Design System Checklist',
    description: 'A checklist to ensure your design system is comprehensive and well-documented.',
    preview: 'design-system-checklist.png',
    link: 'https://designsystemchecklist.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Ingradients',
    description: 'A gallery of mesh gradients.',
    preview: 'ingradients.png',
    link: 'https://ingradients.net/',
    tags: ['design'],
  },
  {
    name: 'Design Gradients',
    description: 'A collection of beautiful gradients for your designs.',
    preview: 'design-gradients.png',
    link: 'https://designgradients.com/',
    tags: ['design'],
  },
  {
    name: 'Paper Sizes',
    description: 'A collection of common paper sizes and dimensions.',
    preview: 'paper-sizes.png',
    link: 'https://papersizes.io/',
    tags: ['design'],
  },
  {
    name: 'Shoot',
    description: 'A collection of app screenshots for design inspiration.',
    preview: 'shoot.png',
    link: 'https://shoot.design/',
    tags: ['design'],
  },
  {
    name: 'Navbar Gallery',
    description: 'A collection of beautifully designed navigation bars for your applications.',
    preview: 'navbar-gallery.png',
    link: 'https://navbar.gallery/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Colormind',
    description: 'A color scheme generator powered by AI.',
    preview: 'colormind.png',
    link: 'https://colormind.io/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Brandmark',
    description: 'A logo design tool powered by AI.',
    preview: 'brandmark.png',
    link: 'https://brandmark.io/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Huemint',
    description: 'A color palette generator powered by AI.',
    preview: 'huemint.png',
    link: 'https://huemint.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Font Joy',
    description: 'A font pairing tool powered by AI.',
    preview: 'font-joy.png',
    link: 'https://fontjoy.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Vecto3d',
    description: 'A 3D vector graphics tool.',
    preview: 'vecto3d.png',
    link: 'https://vecto3d.xyz/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Fontscale',
    description: 'A tool for responsive font scaling.',
    preview: 'fontscale.png',
    link: 'https://fontscale.joelfisher.me/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Animate UI',
    description: 'A library of fluid, animated components.',
    preview: 'animate-ui.png',
    link: 'https://animate-ui.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Pattern Craft',
    description: 'A gallery of patterns and textures.',
    preview: 'pattern-craft.png',
    link: 'https://patterncraft.fun/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Mintlify',
    description: 'A documentation generator powered by AI.',
    preview: 'mintlify.png',
    link: 'https://mintlify.com/',
    tags: ['design', 'dev'],
  },
  {
    name: 'Signature PDF',
    description: 'A tool for creating and signing PDF documents.',
    preview: 'signature-pdf.png',
    link: 'https://pdf.24eme.fr/',
    tags: ['design', 'dev'],
  },
];
